# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.network "private_network", ip: "192.168.10.100"
    app.hostsupdater.aliases = ["development.local"]
    app.vm.synced_folder "environment/app", "/home/ubuntu/app"
    app.vm.synced_folder "node-sample-app-master", "/home/ubuntu/node-sample-app"
    app.vm.provision "shell", path: "environment/app/provision.sh", privileged: false
    config.vm.network "forwarded_port", host: 3000, guest: 80
    app.vm.provision "shell", inline: "echo DB_HOST = 192.168.10.150 >> .bashrc"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "192.168.10.150"
    db.hostsupdater.aliases = ["database.local"]
    db.vm.synced_folder "environment/db", "/home/ubuntu/environment"
    db.vm.provision "shell", path: "environment/db/provision.sh", privileged: false
  end
end
